### PR TITLE
Improvments

### PR DESCRIPTION
**Pull request by robertsLando**
- Bumped deps
- Added qlobber `match_empty_levels` flag
- Fixed tests
- Release script

### CODE REVIEW

**Comment by robertsLando** [comment]
Should I create a minor or a major of this once merged?

**Comment by mcollina** [comment]
this seems to be a minor, is it a breaking change?

**Comment by robertsLando** [comment]
escape-string-regexp drops nodejs 8 support. I will also remove it from github action tomorrow. So I think it should be a major

**Comment by mcollina** [comment]
Make it a major
Il 2 mar 2020, 20:30 +0100, Daniel Lando <notifications@github.com>, ha scritto:
> escape-string-regexp drops nodejs 8 support. I will also remove it from github action tomorrow. So I think it should be a major
>

**Comment by robertsLando** [comment]
Could you also check the PR #33 of this repo? I would like to merge that too before the release

**Comment by robertsLando** [comment]
@mcollina  Still LGTM? Can I go on with this and make a major release?

**Comment by robertsLando** [comment]
@mcollina ping

**Comment by robertsLando** [comment]
@mcollina Major release? We have dropped nodejs 8 here

**Comment by mcollina** [comment]
definitely!
Il 17 mar 2020, 08:47 +0100, Daniel Lando <notifications@github.com>, ha scritto:

**Comment by robertsLando** [comment]
Wait a moment there are some outdated deps

**Pull request merged**
