### PR TITLE
feat: Add incoming and outgoing collection query indexes

### PR DESCRIPTION
**Pull request by scagood**
This addes the indexes from #64

### CODE REVIEW

**Comment by scagood** [comment]
:thinking: It works on mongo 4.0 not mongo 4.4 due to the `expireAfterSeconds` being present in the index options object, fixing then force pushing.

**Comment by scagood** [comment]
I have tested in node 10, 12, 13, and 14 against mongo 4.0, 4.2, and 4.4 and I cant reproduce this error in the CI. (Ive done node 13 <-> mongo 4.4 many times now :sweat:)

This is the failing test [aedes-persistence/abstract.js:770](https://github.com/moscajs/aedes-persistence/blob/master/abstract.js#L770). I think the `subscriptionsByClient` response is valid as it contains the correct subscriptions just in a different order.

This could be resolved by adding a `.sort()` call or something, but I think the abstract test should be changed instead.

**Comment by mcollina** [comment]
Totally, could you send a PR to the abstract tests making that check order independent?

**Comment by scagood** [comment]
:thinking: `aedes-persistence` is not in the `package.json`, should I add it there as a dev dependency?

**Comment by robertsLando** [comment]
It is not there because it is a dep of aedes-cached-persistence, you should run npm update --depth 1 I think would be enough, I will bump aedes-cached-persistence too

**Comment by robertsLando** [comment]
https://github.com/moscajs/aedes-cached-persistence/pull/46

**Comment by robertsLando** [comment]
@scagood You can now bump aedes-cached-persistence to 8.1.1

**Review by robertsLando — APPROVED** [review]
LGTM

**Comment by scagood** [comment]
Closes #64

**Comment by robertsLando** [comment]
@mcollina ping?

**Review by mcollina — COMMENTED** [review]
lgtm

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by robertsLando** [comment]
@scagood Released :tada:

**Comment by robertsLando** [comment]
@scagood Are you interested to join our moscajs org? Actually I'm the only maintainer and every help would be more then welcome, @mcollina is the author of aedes but doesn't have time to contribute with the code, just code reviews

**Comment by scagood** [comment]
I'm totally happy to contribute code (and review code) where needed, but Im not sure I want to be a maintainer at this point as I dont really have the time to dedicate to it, thank you for the offer though :sweat_smile:

**Pull request merged**
